<?php
// auto-generated by sfPropelCrud
// date: 2010/11/20 13:48:59
// account_types: bid, won, not_won, watch, watch_cl, sell, sold, not_sold, future
?>
<h1>My Account</h1>

<ul>
    <li><?php echo link_to('bid', 'allegro/myAccount?account_type=bid') ?></li>
    <li><?php echo link_to('won', 'allegro/myAccount?account_type=won') ?></li>
    <li><?php echo link_to('not_won', 'allegro/myAccount?account_type=not_won') ?></li>
    <li><?php echo link_to('watch', 'allegro/myAccount?account_type=watch') ?></li>
    <li><?php echo link_to('watch_cl', 'allegro/myAccount?account_type=watch_cl') ?></li>
    <li><?php echo link_to('sell', 'allegro/myAccount?account_type=sell') ?></li>
    <li><?php echo link_to('sold', 'allegro/myAccount?account_type=sold') ?></li>
</ul>

<h3><?php echo $account_type; ?></h3>

<table>
<thead>
<tr>
  <th>id</th>
  <th>nazwa</th>
  <th>cena</th>
  <th>user</th>
</tr>
</thead>
<tbody>
<?php if($my_account_array_items): ?>
<?php foreach ($my_account_array_items as $key => $item): ?>
<tr>
    <?php //var_dump($my_account_array_items[$key]['my-account-array']) ?>
    <td><?php echo $my_account_array_items[$key]['my-account-array'][0] ?></td>
    <td><?php echo $my_account_array_items[$key]['my-account-array'][9] ?></td>
    <td><?php echo $my_account_array_items[$key]['my-account-array'][2] ?></td>
    <td><?php echo $my_account_array_items[$key]['my-account-array'][24].'('.$my_account_array_items[$key]['my-account-array'][11].')' ?></td>
</tr>
<?php endforeach; ?>
<?php endif; ?>
</tbody>
</table>
